/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ftec.chaves.view;

import br.com.ftec.chaves.control.ColaboradorDAO;
import br.com.ftec.chaves.control.ReservaDAO;
import br.com.ftec.chaves.control.SalaDAO;
import br.com.ftec.chaves.model.Colaborador;
import br.com.ftec.chaves.model.Reserva;
import br.com.ftec.chaves.model.Sala;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADM
 */
public class FrmReservarSala extends javax.swing.JFrame {

    /**
     * Creates new form FrmReservarSala
     */
    public FrmReservarSala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbColaboradorresp = new javax.swing.JLabel();
        lbCadastroSalas = new javax.swing.JLabel();
        lbSala = new javax.swing.JLabel();
        lbDiaSemana = new javax.swing.JLabel();
        fteclogo = new javax.swing.JLabel();
        ibgenlogo = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        bntReservar = new javax.swing.JButton();
        cmbTurno = new javax.swing.JComboBox<>();
        lbTurno = new javax.swing.JLabel();
        cmbSala = new javax.swing.JComboBox<>();
        cmbDia = new javax.swing.JComboBox<>();
        cmbResponsavel = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbReservas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbColaboradorresp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbColaboradorresp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbColaboradorresp.setText("Responsavel");

        lbCadastroSalas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbCadastroSalas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCadastroSalas.setText("RESERVA DE SALAS");

        lbSala.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbSala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSala.setText("Sala:");

        lbDiaSemana.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbDiaSemana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDiaSemana.setText("Dia da Semana");

        fteclogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ftec/chaves/view/resources/logo_ftec.png"))); // NOI18N

        ibgenlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ftec/chaves/view/resources/logo_ibgen.png"))); // NOI18N
        ibgenlogo.setText("jLabel3");

        lbSenha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSenha.setText("Senha");

        bntReservar.setText("Reservar");
        bntReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntReservarActionPerformed(evt);
            }
        });

        cmbTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));
        cmbTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTurnoActionPerformed(evt);
            }
        });

        lbTurno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTurno.setText("Turno");

        cmbSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segunda-Feira", "Terça-feiral", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado", "Domingo" }));

        cmbResponsavel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbReservas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCadastroSalas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fteclogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ibgenlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbDiaSemana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbSala, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTurno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDia, javax.swing.GroupLayout.Alignment.TRAILING, 0, 102, Short.MAX_VALUE)
                            .addComponent(cmbSala, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTurno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbColaboradorresp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bntReservar)))
                        .addGap(138, 138, 138))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCadastroSalas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSala)
                    .addComponent(lbColaboradorresp)
                    .addComponent(cmbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiaSemana)
                    .addComponent(lbSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntReservar)
                    .addComponent(cmbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTurno))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ibgenlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fteclogo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntReservarActionPerformed
        // TODO add your handling code here:

        Reserva r = new Reserva();

        r.setDia(cmbDia.getSelectedItem().toString());
        r.setTurno(cmbTurno.getSelectedItem().toString());

        ColaboradorDAO c = new ColaboradorDAO();
        SalaDAO s = new SalaDAO();

        try {
            Colaborador a = c.buscaColaboradorCpf(cmbResponsavel.getSelectedItem().toString());
            r.setColaborador(a);
            r.setSala(s.buscaSalaPorSala(cmbSala.getSelectedItem().toString()));
            ReservaDAO dao = new ReservaDAO();
            dao.salvar(r);
        } catch (Exception ex) {
            Logger.getLogger(FrmReservarSala.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_bntReservarActionPerformed

    private void cmbTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTurnoActionPerformed

    public void montaTabela() throws Exception {

        DefaultTableModel dftm = (DefaultTableModel) tbReservas.getModel();
        dftm.setNumRows(0);

        tbReservas.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbReservas.getColumnModel().getColumn(0).setHeaderValue("Colaborador");
            
        tbReservas.getColumnModel().getColumn(1).setPreferredWidth(20);
            tbReservas.getColumnModel().getColumn(1).setHeaderValue("Dia");
            
        tbReservas.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbReservas.getColumnModel().getColumn(2).setHeaderValue("Sala");
            
        tbReservas.getColumnModel().getColumn(3).setPreferredWidth(20);
            tbReservas.getColumnModel().getColumn(3).setHeaderValue("Turno");
        ReservaDAO dao = new ReservaDAO();

        for (Reserva r : dao.listaReservas()) 
            dftm.addRow(new Object[]{
                r.getColaborador().getId(),
                r.getDia(),
                r.getSala().getId(),
                r.getTurno()}
            
           );

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReservarSala.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReservarSala.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReservarSala.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReservarSala.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                FrmReservarSala r = new FrmReservarSala();
                try {
                    r.montaComboColaborador();
                    r.montaComboSala();
                    r.montaTabela();

                } catch (Exception ex) {
                    Logger.getLogger(FrmReservarSala.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
                r.setVisible(true);
            }
        });
    }

    public void montaComboSala() throws Exception {

        List<Sala> listaSalaObjeto = new ArrayList<>();
        List<String> listaSalaDescricao = new ArrayList<>();

        SalaDAO salaDao = new SalaDAO();
        listaSalaObjeto = salaDao.listaSalas();

        for (int i = 0; i < listaSalaObjeto.size(); i++) {
            listaSalaDescricao.add(listaSalaObjeto.get(i).getSala());
        }

        DefaultComboBoxModel dfcmb = new DefaultComboBoxModel(listaSalaDescricao.toArray());
        cmbSala.setModel(dfcmb);

    }

    public void montaComboColaborador() throws Exception {

        List<Colaborador> listaColaboradorObjeto = new ArrayList<>();
        // List<String> listaColaboradorNome = new ArrayList<>();
        ColaboradorDAO colaboradorDao = new ColaboradorDAO();
        listaColaboradorObjeto = colaboradorDao.listaColaboradores();

        /*for ( int i = 0 ; i< listaColaboradorObjeto.size(); i++){
            listaColaboradorNome.add(listaColaboradorObjeto.get(i).getNome());
        } deletar isso após criar o metodo toString();*/
        DefaultComboBoxModel dfcmb = new DefaultComboBoxModel(listaColaboradorObjeto.toArray());
        cmbResponsavel.setModel(dfcmb);

        //criar o método toString();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntReservar;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbResponsavel;
    private javax.swing.JComboBox<String> cmbSala;
    private javax.swing.JComboBox<String> cmbTurno;
    private javax.swing.JLabel fteclogo;
    private javax.swing.JLabel ibgenlogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCadastroSalas;
    private javax.swing.JLabel lbColaboradorresp;
    private javax.swing.JLabel lbDiaSemana;
    private javax.swing.JLabel lbSala;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTurno;
    private javax.swing.JTable tbReservas;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
